import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "@/src/i18n/routing";
import Navigation from "@/src/components/Navigation";

import Providers from "@/src/providers/Provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

export default async function LocaleLayout({ children, params }: Props) {
  // Ensure that the incoming `locale` is valid
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    console.log(locale);
    notFound();
  }
  {
    return (
      <html
        lang={locale}
        className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      >
        <body className="min-h-screen bg-neutral-50 dark:bg-neutral-950 font-sans flex flex-col text-neutral-900 dark:text-neutral-50 transition-colors duration-300">
          <Providers>
            <NextIntlClientProvider>
              <Navigation />
              <main className="flex-grow flex flex-col">
                {children}
              </main>
              {/* Simple Footer */}
              <footer className="py-6 text-center text-neutral-500 dark:text-neutral-400 text-sm border-t border-neutral-200 dark:border-neutral-800">
                © {new Date().getFullYear()} Our Platform. All rights reserved.
              </footer>
            </NextIntlClientProvider>
          </Providers>
        </body>
      </html>
    );
  }
}
